const informacion = {
	orco: {
		vidaInicial: 20,
		promedio: {
			mago: 7,
			paladin: 9.5,
			bardo: 8,
			ladron: 7.5,
			pirata: 9.5,
			trabajador: 8,
			asesino: 8.5,
			bandido: 8.5,
			clerigo: 8,
			guerrero: 10,
			cazador: 9.5,
		},
	},
	elfo: {
		vidaInicial: 19,
		promedio: {
			mago: 6.5,
			paladin: 9,
			bardo: 7.5,
			ladron: 7,
			pirata: 9,
			trabajador: 7.5,
			asesino: 8,
			bandido: 8,
			clerigo: 7.5,
			guerrero: 9.5,
			cazador: 9,
		},
	},
	elfoOscuro: {
		vidaInicial: 19,
		promedio: {
			mago: 6.5,
			paladin: 9,
			bardo: 7.5,
			ladron: 7,
			pirata: 9,
			trabajador: 7.5,
			asesino: 8,
			bandido: 8,
			clerigo: 7,
			guerrero: 9.5,
			cazador: 9,
		},
		gnomo: {
			vidaInicial: 18,
			promedio: {
				mago: 6,
				paladin: 8.5,
				bardo: 7,
				ladron: 6.5,
				pirata: 8.5,
				trabajador: 7,
				asesino: 7.5,
				bandido: 7.5,
				clerigo: 7,
				guerrero: 9,
				cazador: 8.5,
			},
		},
	},
	enano: {
		vidaInicial: 21,
		promedio: {
			mago: 7.5,
			paladin: 10,
			bardo: 8.5,
			ladron: 8,
			pirata: 10,
			trabajador: 8.5,
			asesino: 9,
			bandido: 9,
			clerigo: 8.5,
			guerrero: 10.5,
			cazador: 10,
		},
	},
};

// console.log(informacion);
